In [31]:
import tensorflow as tf
tf .__version__

'2.11.0'

In [43]:
!pip install IPython 
from IPython.display import Image

In [4]:
#-*- coding: utf-8 -*-

from tensorflow.keras.datasets import mnist
# tensorflow에서 직접 MNIST 손글씨 이미지 dataset을 불러와서 사용함.

from tensorflow.keras.utils import to_categorical
# tensorflow의 keras API에 있는 util 클래스로부터 to_categorical() 함수 불러오기.

from tensorflow.keras.models import Sequential
# tensorflow의 keras API에서 필요한 함수들 불러오기

from tensorflow.keras.layers import Dense
# Data를 다루는데 필요한 library를 불러오기

In [5]:
from tensorflow.keras.callbacks import ModelCheckpoint,EarlyStopping

학습을 조기 종료할지 지정하는 parameter값을 적당히 설정해야함.

이때 parameter 값을 너무 크게 설정하여 과적합 진행 이후 학습이 중단되어 버리는 문제 생길 수 있음.

위와 같은 문제 해결을 위해 모델을 에포크마다 자동으로 저장해주는 ModelCheckpoint 함수 사용.

In [6]:
import matplotlib.pyplot as plt
import numpy
import os
# 운영체제에서 제공되는 여러 기능을 파이썬에서 수행할 수 있게 함.
import tensorflow as tf
# tensorflow 라이브러리 불러옴.

In [21]:
# seed 값 설정
seed = 0
numpy.random.seed(seed)
tf.random.set_seed(3)

특정 seed값 0으로 설정.
numpy의 rand함수로 3개의 난수를 생성.
rand 함수는 0~1 사이의 난수값을 입력받은 인수만큼 발생시킴.

In [22]:
# MNIST 데이터 불러오기
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [28]:
Y_train[:104]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1, 5, 7, 1, 7], dtype=uint8)

In [29]:
X_train[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  51, 159, 253, 159,  50,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  48, 238, 252, 252, 252, 237,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

MNIST 데이터셋을 인터넷을 통해 가져옴.

불러온 이미지 데이터는 X, 이미지에 0~9를 붙인 이름표를 Y로 구분.

Keras의 MNIST 데이터는 총 7만 개 이미지 중 6만 개를 학습용, 1만 개를 테스트용으로 미리 구분.
 
위의 변수들은 각각 60000x784, 60000x1, 10000x784, 10000x1의 크기로 각각이 1차원 배열로 되어 있다.

#학습에 사용될 데이터 : X_train, Y_train

#테스트에 사용될 부분 :X_test, Y_test

In [30]:
X_train = X_train.reshape(X_train.shape[0], 784).astype('float32') / 255
X_test = X_test.reshape(X_test.shape[0], 784).astype('float32') / 255

reshape을 해서 2차원 배열로 바꾸고 0 - 255의 정수값을 astype('float32') / 255.0 으로 0~1사이의 값으로 바꿈.(float32로 정규화)

이때 사이즈가 더 커지며, 딥러닝을 할 때 정규화해서 넣어야 더 잘됨.

In [31]:
Y_train = to_categorical(Y_train, 10)
Y_test = to_categorical(Y_test, 10)

In [34]:
Y_train[:5] # 50419 순서로 1이 나옴.

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

to_categorial 함수 사용 : 하나만 High(1) 상태이고 다른 것은 Low(0) 상태인 데이터로 바꾸어줌.

Y_train, Y_test는 바꾸고자 하는 데이터 셋을, 10은 레이블 수를 입력하면 됨.

softmax 함수가 적합.

In [11]:
# 모델 프레임 설정
model = Sequential()
model.add(Dense(16, input_dim=784, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='softmax'))

입력값(input dim)이 784개, 은닉층이 16개, 은닉층 16개, 출력이 10개로 총 826개인 모델. 
활성화 함수로 은닉층에서 relu를, 출력층에서는 softmax를 사용.

784*16+16*16+16*10 =

Modeling 중 Sequential()은 Keras에서 입력층, 은닉층, 출력층 구성하기 위해 사용.

Sequential()을 model로 선언 후 model.add()를 사용하여 층들을 추가.

Dense() :출력층. 뉴런의 입력과 출력을 연결. 입력 뉴런 수에 관계없이 출력 뉴런 수 자연스럽게 설정O.

activation = 활성화 함수.
- relu : 은닉층.
- sigmoid : 출력층. 주로 이진분류 문제에서 쓰임.
- softmax : 출력층. 셋 이상의 선택지 중 1택하는 다중 클래스 분류 문제에 자주 쓰임.

In [12]:
# 모델 실행 환경 설정
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                12560     
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 10)                170       
                                                                 
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


딥러닝 실행 환경 : 오차함수 categorial_crossentropy, 최적화 함수 adam 사용.

모델 실행에 앞서 먼저 성과 저장. 

In [13]:
# 모델의 실행
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=5, batch_size=200)

Epoch 1/5
300/300 [==============================] - 2s 4ms/step - loss: 0.8716 - accuracy: 0.7352 - val_loss: 0.3435 - val_accuracy: 0.9047
Epoch 2/5
300/300 [==============================] - 1s 4ms/step - loss: 0.3083 - accuracy: 0.9137 - val_loss: 0.2658 - val_accuracy: 0.9241
Epoch 3/5
300/300 [==============================] - 1s 3ms/step - loss: 0.2501 - accuracy: 0.9297 - val_loss: 0.2385 - val_accuracy: 0.9325
Epoch 4/5
300/300 [==============================] - 1s 4ms/step - loss: 0.2223 - accuracy: 0.9373 - val_loss: 0.2194 - val_accuracy: 0.9373
Epoch 5/5
300/300 [==============================] - 1s 3ms/step - loss: 0.2031 - accuracy: 0.9420 - val_loss: 0.2034 - val_accuracy: 0.9417


epochs=5 : 각 샘플이 처음부터 끝까지 다섯 번 재사용될 때까지 실행 반복.

batch_size=200 : 전체 샘플을 200개씩 끊어서 집어넣기. 

batch_size는 너무 크거나 작으면 문제가 생기므로 자신의 컴퓨터가 감당할 만큼의 적당한 크기를 찾아 설정해줘야함.

In [14]:
# 테스트 정확도 출력
print("\n Test Accuracy: %.4f" % (model.evaluate(X_test, Y_test)[1]))

313/313 [==============================] - 1s 2ms/step - loss: 0.2034 - accuracy: 0.9417

 Test Accuracy: 0.9417


첫 번째 에포크에서 90.36%였던 정확도가 5번째에서 94.03%로 업데이트됨.
테스트하면 94.03%의 정확도를 보여줌.